### PR TITLE
Add hxmath lib to Build Options

### PR DESCRIPTION
**Pull request by AustinEast**
This PR adds the [hxmath library](https://github.com/tbrosman/hxmath) to the available build options.

### CODE REVIEW

**Comment by AlexHaxe** [comment]
hxmath lib has no `src` folder so `hxmath.hxml` is pointing to a non existant path. 
once corrected it complains about missing nanotest library, because of `Test.hx` which pulls in all testcases from project root.

I can fix those after install, but it would be best if `Test.hx` could be moved to `test` folder. 
I reckon everyone using hxmath lib will have type `Test` available in global namespace?

**Comment by AustinEast** [comment]
> I reckon everyone using hxmath lib will have type Test available in global namespace?

Wow. yeah, I just checked in a project and `Test.hx` is indeed available in the namespace. Never noticed that before! I'll raise an issue about it in the repo.

**Comment by AustinEast** [comment]
hxmath’s project structure has been updated so that the namespace issues should no longer be a problem 👍 

should i request a new haxelib release for hxmath, or are we okay with moving forward with a git version?

**Comment by AlexHaxe** [comment]
thanks, I'm fine with a git version

**Comment by AlexHaxe** [comment]
online demo: https://try.haxe.org/#f3c70192

**Pull request merged**
