### PR TITLE
Codemirror patch

### PR DESCRIPTION
**Pull request by RblSb**
htmlmixed/css modes replaced with xml.

There is possibility of auto-indentation bugs when you add `{` to line, not sure if `indent: function` should change something.
Also, we need to fix typing `{<Enter>}` someway. Is there is some other bad cases?

### CODE REVIEW

**Comment by AlexHaxe** [comment]
when typing in try.haxe I sure have noticed some indentation issues, but I usually forget about them almost immediately. I'm usually more annoyed when it autocloses my braces and parenthesis. I don't really like that and it's usually the first thing I turn off in an editor, but I understand that some people might like it and find it helpful. 

I guess we keep iterating and improving over time.

your code appears to run fine on my testsystem, I haven't seen any issues.

**Comment by RblSb** [comment]
Do you think it is fine to merge or i should make pr to codemirror instead? Seems little scary for me, do not understand much from this file.
In future something like monaco or codemirror 6 can be a better option, sad thing we cannot reuse vscode's tmLanguage syntax without wasm.

**Comment by AlexHaxe** [comment]
I think it's fine to merge it. we can battle test haxe.js and send it to codemirror later.

**Comment by RblSb** [comment]
Without squash so you can revert string interpolation if something goes wrong

**Comment by AlexHaxe** [comment]
ok, I've put it online

**Pull request merged**
